# GitHub Pages configuration
title: Writing Bot
description: Enhanced Writing Analysis Based on Classic Guides
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings - disable Jekyll processing for static site
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - README-frontend.md
  - writing_bot.py
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include files that would otherwise be ignored
include:
  - _redirects
